
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Бизнис и менаџмент', 'Зимски', 'Прва');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Вовед во компјутерските науки', 'Зимски', 'Прва');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Професионални вештини', 'Зимски', 'Прва');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Структурно програмирање', 'Зимски', 'Прва');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Педагогија', 'Зимски', 'Прва');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Дискретни структури', 'Зимски', 'Прва');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Калкулус', 'Зимски', 'Прва');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Калкулус 1', 'Зимски', 'Прва');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Дизајн на дигитални кола', 'Зимски', 'Прва');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Физика', 'Зимски', 'Прва');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Дискретна математика', 'Летен', 'Прва');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Компјутерски архитектури', 'Летен', 'Прва');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Објектно-ориентирано програмирање', 'Летен', 'Прва');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Основи на сајбер безбедноста', 'Летен', 'Прва');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Спорт и здравје', 'Летен', 'Прва');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Бизнис статистика', 'Летен', 'Прва');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Калкулус 2', 'Летен', 'Прва');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Компјутерски компоненти', 'Летен', 'Прва');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Креативни вештини за решавање проблеми', 'Летен', 'Прва');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Маркетинг', 'Летен', 'Прва');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Објектно ориентирана анализа и дизајн', 'Летен', 'Прва');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Основи на веб дизајн', 'Летен', 'Прва');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('ИТ системи за учење', 'Летен', 'Прва');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Архитектура и организација на компјутери', 'Летен', 'Прва');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Дискретни структури 2', 'Летен', 'Прва');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Алгоритми и податочни структури', 'Зимски', 'Втора');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Компјутерски мрежи', 'Зимски', 'Втора');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Основи на теоријата на информации', 'Зимски', 'Втора');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Инженерска математика', 'Зимски', 'Втора');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Интернет програмирање на клиентска страна', 'Зимски', 'Втора');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Напредно програмирање', 'Зимски', 'Втора');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Основи на комуникациски системи', 'Зимски', 'Втора');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Управување со техничката поддршка', 'Зимски', 'Втора');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Компјутерски мрежи и безбедност', 'Зимски', 'Втора');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Мултимедијални технологии', 'Зимски', 'Втора');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Веројатност и статистика', 'Зимски', 'Втора');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Дигитизација', 'Зимски', 'Втора');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Шаблони за дизајн на кориснички', 'Зимски', 'Втора');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Економија за ИКТ инженери', 'Зимски', 'Втора');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Безжични и мобилни системи', 'Летен', 'Втора');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Оперативни системи', 'Летен', 'Втора');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Вештачка интелигенција', 'Летен', 'Втора');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Визуелно програмирање', 'Летен', 'Втора');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Вовед во екоинформатиката', 'Летен', 'Втора');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Вовед во случајни процеси', 'Летен', 'Втора');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Интернет технологии', 'Летен', 'Втора');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Медиуми и комуникации', 'Летен', 'Втора');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Одржливи и енергетски ефикасни компјутерски системи', 'Летен', 'Втора');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Софтверско инженерство', 'Летен', 'Втора');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('ИКТ во образованието', 'Летен', 'Втора');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Дизајн на алгоритми', 'Летен', 'Втора');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Е-влада', 'Летен', 'Втора');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Електрични кола', 'Летен', 'Втора');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Компјутерска графика', 'Летен', 'Втора');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Споделување и пресметување во толпа', 'Летен', 'Втора');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Анализа на софтверските барања', 'Летен', 'Втора');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Дигитално процесирање на слика', 'Летен', 'Втора');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Теорија на информации со дигитални комуникации', 'Летен', 'Втора');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Концепти на информатичко општество', 'Летен', 'Втора');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Администрација на системи', 'Зимски', 'Трета');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Бази на податоци,зимски', 'Зимски', 'Трета');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Мрежна безбедност', 'Зимски', 'Трета');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Веб програмирање', 'Зимски', 'Трета');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Визуелизација', 'Зимски', 'Трета');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Вовед во науката за податоци', 'Зимски', 'Трета');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Информациска безбедност', 'Зимски', 'Трета');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Компјутерска етика', 'Зимски', 'Трета');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Компјутерски звук говор и музика', 'Зимски', 'Трета');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Линеарна алгебра и примени', 'Зимски', 'Трета');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Мултимедиски мрежи', 'Зимски', 'Трета');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Основи на роботиката', 'Зимски', 'Трета');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Паралелно и дистрибуирано процесирање', 'Зимски', 'Трета');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Дизајн на образовен софтвер', 'Зимски', 'Трета');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Напреден веб дизајн', 'Зимски', 'Трета');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Линеарна алгебра и примени', 'Зимски', 'Трета');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Паралелно и дистрибуирано процесирање', 'Зимски', 'Трета');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Дизајн и архитектура на софтвер', 'Зимски', 'Трета');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Информациска безбедност', 'Зимски', 'Трета');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Компјутерска електроника', 'Зимски', 'Трета');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Администрација на мрежи', 'Летен', 'Трета');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Виртуелизација', 'Летен', 'Трета');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Агентно-базирани системи', 'Летен', 'Трета');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Безжични мултимедиски системи', 'Летен', 'Трета');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Вградливи микропроцесорски системи', 'Летен', 'Трета');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Вовед во мрежна наука', 'Летен', 'Трета');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Дигитална форензика', 'Летен', 'Трета');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Дизајн на интеракцијата човек-компјутер', 'Летен', 'Трета');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Електронска и мобилна трговија', 'Летен', 'Трета');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Инфраструктурно програмирање', 'Летен', 'Трета');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Континуирана интеграција и испорака', 'Летен', 'Трета');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Криптографија', 'Летен', 'Трета');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Мерење и анализа на интернет сообраќај', 'Летен', 'Трета');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Мултимедиски системи', 'Летен', 'Трета');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Сервисно ориентирани архитектури', 'Летен', 'Трета');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Софтверски дефинирана безбедност', 'Летен', 'Трета');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Персонализирано учење', 'Летен', 'Трета');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Психологија на училишна возраст', 'Летен', 'Трета');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Работа со надарени ученици', 'Летен', 'Трета');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Дигитални библиотеки', 'Летен', 'Трета');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Софтверски квалитет и тестирање', 'Летен', 'Трета');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Учење на далечина', 'Летен', 'Трета');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Дизајн на интеракцијата човек-компјутер', 'Летен', 'Трета');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Машинско учење', 'Летен', 'Трета');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Формални јазици и автомати', 'Летен', 'Трета');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Географски информациски системи', 'Летен', 'Трета');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Интегрирани системи', 'Летен', 'Трета');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Паралелно програмирање', 'Летен', 'Трета');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Податочно рударство', 'Летен', 'Трета');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Процесирање на сигналите', 'Летен', 'Трета');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Процесна роботика', 'Летен', 'Трета');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Современи компјутерски архитектури', 'Летен', 'Трета');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Статистичко моделирање', 'Летен', 'Трета');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Процесирање на сигналите', 'Летен', 'Трета');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Електронска и мобилна трговија', 'Летен', 'Трета');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Интегрирани системи', 'Летен', 'Трета');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Формални јазици и автомати', 'Летен', 'Трета');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Дистрибуирани системи', 'Зимски', 'Четврта');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Пресметување во облак', 'Зимски', 'Четврта');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Администрација на бази на податоци', 'Зимски', 'Четврта');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Анализа и дизајн на ИС', 'Зимски', 'Четврта');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Веб базирани системи', 'Зимски', 'Четврта');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Вовед во биоинформатиката', 'Зимски', 'Четврта');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Вовед во паметни градови', 'Зимски', 'Четврта');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Дигитална постпродукција', 'Зимски', 'Четврта');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Дистрибуирано складирање на податоци', 'Зимски', 'Четврта');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Имплементација на системи со слободен и отворен код', 'Зимски', 'Четврта');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Иновации во ИКТ', 'Зимски', 'Четврта');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Машинска визија', 'Зимски', 'Четврта');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Методологија на истражувањето во ИКТ', 'Зимски', 'Четврта');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Мобилни информациски системи', 'Зимски', 'Четврта');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Мобилни платформи и програмирање', 'Зимски', 'Четврта');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Мрежна и мобилна форензика', 'Зимски', 'Четврта');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Оптички мрежи', 'Зимски', 'Четврта');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Софтверски дефинирани мрежи', 'Зимски', 'Четврта');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Интернет на нештата', 'Зимски', 'Четврта');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Напредна интеракција човек компјутер', 'Зимски', 'Четврта');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Програмирање на видео игри', 'Зимски', 'Четврта');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Социјални мрежи и медиуми', 'Зимски', 'Четврта');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Програмски парадигми', 'Зимски', 'Четврта');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Автономна роботика', 'Зимски', 'Четврта');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Вовед во анализа на временските серии', 'Зимски', 'Четврта');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Вовед во препознавање на облици', 'Зимски', 'Четврта');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Менаџмент информациски системи', 'Зимски', 'Четврта');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Моделирање и симулација', 'Зимски', 'Четврта');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Обработка на природните јазици', 'Зимски', 'Четврта');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Операциони истражувања', 'Зимски', 'Четврта');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Рударење на масивни податоци', 'Зимски', 'Четврта');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Системи за поддршка при одлучувањето', 'Зимски', 'Четврта');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Софтвер за вградливи системи', 'Зимски', 'Четврта');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Компјутерски поддржано производство', 'Зимски', 'Четврта');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Блоковски вериги и криптовалути', 'Летен', 'Четврта');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Веб пребарувачки системи', 'Летен', 'Четврта');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Географски информациски системи', 'Летен', 'Четврта');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Етичко хакирање', 'Летен', 'Четврта');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Интелигентни системи', 'Летен', 'Четврта');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Мобилни апликации', 'Летен', 'Четврта');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Моделирање и менаџирање на бизнис процеси', 'Летен', 'Четврта');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Модерни трендови во роботика', 'Летен', 'Четврта');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Напредни бази на податоци', 'Летен', 'Четврта');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Напредни теми од криптографија', 'Летен', 'Четврта');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Неструктурирани бази на податоци', 'Летен', 'Четврта');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Претприемништво', 'Летен', 'Четврта');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Складови на податоци и аналитичка обработка', 'Летен', 'Четврта');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Споделување и пресметување во толпа', 'Летен', 'Четврта');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Управување со ИКТ проекти', 'Летен', 'Четврта');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Дизајн на компјутерски мрежи', 'Летен', 'Четврта');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Македонски јазик', 'Летен', 'Четврта');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Методика на информатиката', 'Летен', 'Четврта');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Виртуелна реалност', 'Летен', 'Четврта');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Вовед во когнитивни науки', 'Летен', 'Четврта');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Компјутерска анимација', 'Летен', 'Четврта');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Биолошки инспирирано пресметување', 'Летен', 'Четврта');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('ИКТ за развој', 'Летен', 'Четврта');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Интелигентни информациски системи', 'Летен', 'Четврта');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Пресметковна биологија', 'Летен', 'Четврта');
INSERT INTO subject ("name", "semester_type", "year") VALUES ('Програмски јазици и компајлери', 'Летен', 'Четврта');

